### ISSUE TITLE
After upgrading some packages, Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by raduungurean** [bizz84/simple_auth_flutter_riverpod#1]
Hello,

======== Exception caught by widgets library =======================================================
The following JSRangeError was thrown building AuthScreen(dirty, dependencies: [UncontrolledProviderScope], state: _ConsumerState#748dd):
Invalid argument: Maximum call stack size exceeded

The relevant error-causing widget was: 
  AuthScreen AuthScreen:file:///C:/flutter_projects/auth/lib/src/app.dart:16:19
When the exception was thrown, this was the stack: 
packages/riverpod/src/framework/auto_dispose.dart 7:24                                                                  <computed>
packages/riverpod/src/stream_provider/base.dart 110:56                                                                  __
packages/riverpod/src/stream_provider/auto_dispose.dart 42:7 

pubspec.yaml
-------
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  rxdart: ^0.27.3
```
